### ISSUE TITLE
problem with syntax-check-linter.js

### ISSUE THREAD

**Issue by jdoege** [azawawi/atom-perl6-editor-tools#27]
When there are no lint errors, the module throws this error:

TypeError: Cannot read property 'endsWith' of undefined

TypeError: Cannot read property 'endsWith' of undefined
    at /home/jdoege/.atom/packages/atom-perl6-editor-tools/lib/syntax-check-linter.js:38:24

Looking in the file (lines 38-40) shows: 

```
  if (output.stdout.endsWith("Syntax OK\n") && output.stderr == "") {
    return []
  }
```

**Comment by jdoege** [comment]
The original entry was a result of running on Ubuntu. I just checked this on a Mac and I get the same error there, too.

**Comment by jdoege** [comment]
Adding that this is problematic because a new error and dialog that must be dismissed is issued with every small change to the text being edited.

**Comment by jdoege** [comment]
And, just for clarity, what I mean by, "When there are no lint errors," is that that error doesn't get thrown if there are lint errors in the edited code that (rightly) produces other dialog boxes.

**Comment by kmwallio** [comment]
I believe this is fixed.  If you go into your atom packages directory ~/.atom/packages/atom-perl6-editor-tools, and replace the lib/syntax-check-linter.js with the one in this repo, it should fix the issue.

**Comment by jabowery** [comment]
It's still a problem.

I just installed atom on Ubuntu 16.04 LTS and then installed first `language-perl6fe` then `atom-perl6-editor-tools` via the built in installer.

**Comment by azawawi** [comment]
Fixed. Please update. Sorry for being late 👍
